/*
 * This source file was generated by the Gradle 'init' task
 */
package org.zeus.ims;

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.ActiveProfiles;

@SpringBootTest
@ActiveProfiles("test")
class InventoryManagementApplicationTest {

    @Test
    void contextLoads() {
        // This test will fail if the application context cannot start
        // It's a basic smoke test to ensure the Spring Boot application can load
    }
}
